# Generated by Django 3.2.4 on 2021-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_dramatic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dramatic',
        ),
    ]
